services:
  axon:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      - "axoniq.axonserver.standalone=true"
      - "axoniq.axonserver.devmode.enabled=true"